_BASE_: "../Base_det.yaml"

MODEL:
  WEIGHTS: "output/R50/150k_tt_mlt_13_15/pretrain/model_final.pth"
  TRANSFORMER:
    INFERENCE_TH_TEST: 0.3

  
DATASETS:
  TRAIN: ("ic15_train",)
  TEST: ("ic15_test",)

SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 1e-4
  LR_BACKBONE: 1e-5
  WARMUP_ITERS: 0
  STEPS: (300000,)
  MAX_ITER: 400000
  CHECKPOINT_PERIOD: 200000

TEST:
  EVAL_PERIOD: 100000000

OUTPUT_DIR: "output/R50/150k_tt_mlt_13_15/pretrain/ic15"
