MODEL:
  META_ARCHITECTURE: "OneStageRCNN"
  BACKBONE:
    NAME: "build_fcos_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  PROPOSAL_GENERATOR:
    NAME: "BAText"
  FCOS:
    NMS_TH: 0.5
    THRESH_WITH_CTR: False
    USE_SCALE: False
    NUM_CLASSES: 1
    INFERENCE_TH_TRAIN: 0.7
    INFERENCE_TH_TEST: 0.45
  ROI_HEADS:
    NAME: "TextHead"
    IOU_THRESHOLDS: [0.5]
SOLVER:
  CLIP_GRADIENTS:
    ENABLED: True
INPUT:
  HFLIP_TRAIN: False
  MIN_SIZE_TRAIN: (1280, 1312, 1344, 1376, 1408, 1440, 1472, 1504, 1536, 1568, 1600, 1632, 1664, 1696, 1728, 1760, 1792, 1824, 1856, 1888, 1920, 1952, 1984, 2016, 2048)
  MAX_SIZE_TRAIN: 2880
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 2880

  CROP:
    ENABLED: True
    CROP_INSTANCE: True  
    SIZE: [0.3, 0.5] 
    