_BASE_: "../Base_det.yaml"

#MODEL:
  #WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  #WEIGHTS: "/home/ubuntu/res50_pretrain_synth-tt-mlt-13-15-textocr.pth"
  #TRANSFORMER:
  #  INFERENCE_TH_TEST: 0.3


DATASETS:
  TRAIN: ("on_site_train",)
  TEST: ("icdar2015_test",)

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 2e-4
  LR_BACKBONE: 1e-5
  WARMUP_ITERS: 1000  # 轻微增加预热迭代
  STEPS: (40000, 60000)  # 在训练的中间和后期降低学习率
  MAX_ITER: 80000  # 根据你的数据集调整总迭代次数
  CHECKPOINT_PERIOD: 2000

TEST:
  EVAL_PERIOD: 100000000

OUTPUT_DIR: "output/R50/150k_tt_mlt_13_15/pretrain_tiny"



