_BASE_: "../Base_det.yaml"

MODEL:
  #WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  WEIGHTS: "/home/ubuntu/res50_pretrain_synth-tt-mlt-13-15-textocr.pth"
  TRANSFORMER:
    INFERENCE_TH_TEST: 0.3


DATASETS:
  TRAIN: ("on_site_train",)
  TEST: ("icdar2015_test",)

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 1e-4
  LR_BACKBONE: 1e-5
  WARMUP_ITERS: 0
  STEPS: (240000,)
  MAX_ITER: 290000
  CHECKPOINT_PERIOD: 10000

TEST:
  EVAL_PERIOD: 100000000

OUTPUT_DIR: "output/R50/150k_tt_mlt_13_15/pretrain"